import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const references = path.join(root, "references");
const extractedMedia = path.join(root, ".content-build", "word", "media");
const mapDirectory = path.join(root, "assets", "maps");

const sourceHtml = await fs.readFile(path.join(references, "official-game-rules.html"), "utf8");
const mainMatch = sourceHtml.match(/<main>[\s\S]*?<h1>([\s\S]*?)<\/main>/i);
if (!mainMatch) throw new Error("Could not find the official rules content.");

let officialRules = `<h1>${mainMatch[1]}`
  .replace(/<script[\s\S]*?<\/script>/gi, "")
  .replace(/href="questions"/g, 'href="questions.html"')
  .replace(/href="\//g, 'href="')
  .trim();

const moduleText = `// Generated by scripts/build-content.mjs. Edit the source HTML in references/, then rebuild.\nexport const officialRulesHtml = ${JSON.stringify(officialRules)};\n`;
await fs.writeFile(path.join(root, "data", "official-rules.js"), moduleText);

await fs.rm(path.join(root, ".content-build"), { recursive: true, force: true });
await fs.mkdir(path.join(root, ".content-build"), { recursive: true });

const { execFile } = await import("node:child_process");
const { promisify } = await import("node:util");
await promisify(execFile)("unzip", ["-q", path.join(references, "Jet-Lag-H-S-SF-Rule-Modifications.docx"), "-d", path.join(root, ".content-build")]);
await fs.mkdir(mapDirectory, { recursive: true });

const imageMap = {
  "image8.png": "boundaries.webp",
  "image14.png": "hiding-zones.webp",
  "image3.png": "supervisor-districts.webp",
  "image5.jpg": "parking-permit-areas.webp",
  "image16.png": "nearest-mountain.webp",
  "image13.png": "nearest-dog-park.webp",
  "image2.png": "nearest-aquarium.webp",
  "image10.png": "nearest-golf-course.webp",
  "image15.png": "nearest-movie-theater.webp",
  "image6.png": "nearest-hospital.webp",
  "image12.png": "nearest-library.webp",
  "image9.png": "nearest-consulate-1.webp",
  "image1.png": "nearest-consulate-2.webp",
  "image19.png": "nearest-consulate-3.webp",
  "image17.png": "nearest-consulate-4.webp",
  "image11.png": "nearest-farmers-market.webp",
};

for (const [source, destination] of Object.entries(imageMap)) {
  await sharp(path.join(extractedMedia, source))
    .resize({ width: 1800, withoutEnlargement: true })
    .webp({ quality: 82, effort: 5 })
    .toFile(path.join(mapDirectory, destination));
}

await fs.rm(path.join(root, ".content-build"), { recursive: true, force: true });
console.log(`Built official rules and ${Object.keys(imageMap).length} map assets.`);
